/**
 * The Academic Auditor — Paper Pairs Data
 *
 * JSON schema for the paper pairs (20 sample entries provided; the
 * schema is designed to support the full set of 160 pairs by simply
 * appending additional objects that follow the same structure).
 *
 * Schema fields:
 *   id               — unique pair identifier
 *   title_en         — English paper title
 *   title_cn         — Chinese paper title
 *   authors_en       — English authors (string)
 *   authors_cn       — Chinese authors (string)
 *   journal_en       — English journal name
 *   journal_cn       — Chinese journal name
 *   year_en          — English publication year
 *   year_cn          — Chinese publication year
 *   abstract_en      — English abstract
 *   abstract_cn      — Chinese abstract
 *   methodology_key  — shared methodology label
 *   highlights_en    — keywords to highlight in English abstract
 *   highlights_cn    — keywords to highlight in Chinese abstract
 */

const PAPERS_DATA = [
  {
    id: 1,
    title_en: "Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania",
    title_cn: "最低工资与就业：基于中国制造业省级面板的双重差分研究",
    authors_en: "Card, D. & Krueger, A. B.",
    authors_cn: "陈晓光, 李超, 王芳",
    journal_en: "American Economic Review",
    journal_cn: "经济研究",
    year_en: 1994,
    year_cn: 2015,
    abstract_en: "On April 1, 1992, New Jersey's minimum wage rose from $4.25 to $5.05 per hour. To evaluate the impact of the law we surveyed 410 fast-food restaurants in New Jersey and eastern Pennsylvania before and after the rise. Comparisons of employment growth at stores in New Jersey and Pennsylvania (where the minimum wage was unchanged) provide difference-in-differences estimates of the effect of the higher minimum wage. We find no indication that the rise in the minimum wage reduced employment.",
    abstract_cn: "2004年，中国多个省份相继提高了最低工资标准。本文利用各省最低工资调整时间不同构造自然实验，采用双重差分方法估计最低工资对制造业就业的影响。以未调整省份作为控制组，调整省份为处理组，比较政策前后就业变化，我们发现最低工资上调并未显著减少制造业就业，与部分理论预测不符。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["before and after", "difference-in-differences", "treatment", "control"],
    highlights_cn: ["双重差分", "处理组", "控制组", "自然实验", "政策前后"]
  },
  {
    id: 2,
    title_en: "Does Compulsory School Attendance Affect Schooling and Earnings?",
    title_cn: "义务教育与劳动收入：基于出生季度的工具变量研究",
    authors_en: "Angrist, J. D. & Krueger, A. B.",
    authors_cn: "赖小琴, 孟凡强",
    journal_en: "Quarterly Journal of Economics",
    journal_cn: "经济学季刊",
    year_en: 1991,
    year_cn: 2012,
    abstract_en: "In most states, students are required to enter school in the calendar year in which they turn 6 and are permitted to drop out on their 16th birthday. Students born earlier in the year therefore have more schooling when they reach age 16 than students born later. Using quarter of birth as an instrumental variable for education, we find that an additional year of schooling increases earnings by approximately 7.5 percent.",
    abstract_cn: "本文利用中国1986年颁布的《义务教育法》规定的入学年龄门槛，将出生月份作为教育年限的工具变量。9月1日前后出生的儿童在入学年龄上存在系统性差异，为识别教育收益率提供外生变异。两阶段最小二乘估计结果显示，教育年限每增加一年，劳动收入提升约8.2%，高于OLS估计值。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrumental variable", "quarter of birth", "two-stage least squares", "earnings"],
    highlights_cn: ["工具变量", "两阶段最小二乘", "外生变异", "教育收益率"]
  },
  {
    id: 3,
    title_en: "Schooling and Labor Market Consequences of School Construction in Indonesia",
    title_cn: "希望工程与人力资本积累：农村学校建设的双重差分分析",
    authors_en: "Duflo, E.",
    authors_cn: "范静波, 魏志强",
    journal_en: "American Economic Review",
    journal_cn: "中国农村经济",
    year_en: 2001,
    year_cn: 2014,
    abstract_en: "Between 1973 and 1978 the Indonesian government built over 61,000 primary schools throughout the country. I evaluate the effect of this program by combining differences across regions in the number of schools built with differences across cohorts induced by timing of the program. I find the program had a positive effect on both educational attainment and wages, suggesting school construction can be a cost-effective way to improve human capital.",
    abstract_cn: "1990年代，中国政府实施希望工程，在农村地区大规模新建中小学。本文利用各县建校数量差异与出生队列差异构造双重差分估计量，识别农村学校建设对教育年限和劳动收入的影响。结果显示，每建设10所学校可使当地儿童平均受教育年限提高0.3年，成年后劳动收入增加约5.1%，与印尼文献结论高度一致。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["differences across regions", "differences across cohorts", "program", "treatment"],
    highlights_cn: ["双重差分", "出生队列", "政策评估", "反事实"]
  },
  {
    id: 4,
    title_en: "The Colonial Origins of Comparative Development: An Empirical Investigation",
    title_cn: "历史制度与区域发展：基于地理工具变量的研究",
    authors_en: "Acemoglu, D., Johnson, S. & Robinson, J. A.",
    authors_cn: "徐宝良, 李雷",
    journal_en: "American Economic Review",
    journal_cn: "经济学季刊",
    year_en: 2001,
    year_cn: 2016,
    abstract_en: "We exploit differences in European settler mortality rates as an instrument for institutional quality to estimate the effect of institutions on economic performance. Where Europeans faced high mortality, they set up extractive institutions rather than settler colonies. These institutions persisted. Exploiting variation in settler mortality as an instrumental variable, we document a large positive effect of institutional quality on income per capita.",
    abstract_cn: "本文利用中国历史上省级制度变迁的外生地理因素作为工具变量，识别制度质量对区域经济发展的因果效应。以纬度和历史政区划界为工具变量，通过两阶段最小二乘估计，结果显示制度质量对人均GDP有显著正向因果效应，地理因素满足排他性约束，识别策略有效。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrumental variable", "instrument", "two-stage least squares", "exogenous variation"],
    highlights_cn: ["工具变量", "两阶段最小二乘", "排他性约束", "因果效应"]
  },
  {
    id: 5,
    title_en: "Using Geographic Variation in College Proximity to Estimate the Return to Schooling",
    title_cn: "高校扩招与教育回报率：基于地理工具变量的研究",
    authors_en: "Card, D.",
    authors_cn: "王华, 李明辉",
    journal_en: "Aspects of Labour Market Behaviour",
    journal_cn: "经济研究",
    year_en: 1995,
    year_cn: 2014,
    abstract_en: "This paper uses geographic proximity to a college as an instrument for schooling. Men who grew up near a four-year college have significantly higher educational attainment than men who did not. Using the proximity variable as an instrumental variable for completed schooling, I obtain estimates of the return to education of 0.13–0.16, above OLS estimates of 0.07–0.09, suggesting positive ability bias in conventional estimates.",
    abstract_cn: "本文利用1999年中国高等院校扩招政策在各省的差异作为教育年限的工具变量。扩招使高校录取率大幅提升，且各省院校历史密度提供了教育获取的外生变异。工具变量估计显示，教育年限每增加一年，劳动收入增加约10.3%，高于OLS估计值，表明传统估计存在负向选择偏差。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrument", "instrumental variable", "OLS estimates", "proximity"],
    highlights_cn: ["工具变量", "OLS", "选择偏差", "外生变异"]
  },
  {
    id: 6,
    title_en: "The China Syndrome: Local Labor Market Effects of Import Competition in the United States",
    title_cn: "贸易自由化与劳动市场：加入WTO对中国地区就业的影响",
    authors_en: "Autor, D. H., Dorn, D. & Hanson, G. H.",
    authors_cn: "茅静波, 徐明亮",
    journal_en: "American Economic Review",
    journal_cn: "世界经济",
    year_en: 2013,
    year_cn: 2018,
    abstract_en: "We analyze the effect of rising Chinese import competition between 1990 and 2007 on US local labor markets. Using an instrument for trade exposure based on import growth in other high-income countries, we find that local labor markets more exposed to import competition faced higher unemployment, lower labor force participation, and reduced wages. Import competition from China explains one-quarter of the contemporaneous decline in US manufacturing employment.",
    abstract_cn: "本文利用中国2001年加入WTO带来的外生贸易政策冲击，分析贸易自由化对中国地区劳动市场的影响。以其他发展中国家对华出口的变化作为工具变量，采用两阶段最小二乘方法进行估计，结果显示受贸易冲击更大的地区就业结构发生了显著转变，非熟练劳动力工资相对下降。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrument", "local labor markets", "import competition", "two-stage least squares"],
    highlights_cn: ["工具变量", "贸易冲击", "地区劳动市场", "两阶段最小二乘"]
  },
  {
    id: 7,
    title_en: "Regression Discontinuity Designs in Economics",
    title_cn: "政策门槛与经济效应：中国扶贫政策的断点回归分析",
    authors_en: "Lee, D. S. & Lemieux, T.",
    authors_cn: "李卫兵, 张顺明",
    journal_en: "Journal of Economic Literature",
    journal_cn: "经济学季刊",
    year_en: 2010,
    year_cn: 2019,
    abstract_en: "This paper provides a guide to regression discontinuity (RD) designs. The key assumption is that all relevant factors vary smoothly at the cutoff value of the forcing variable, so that any discontinuity in the outcome can be attributed to the treatment. We explain how to implement RD designs and discuss the conditions under which they produce valid causal estimates, including choice of bandwidth and functional form.",
    abstract_cn: "本文利用中国农村扶贫政策以县均收入为核定标准的制度设计，采用断点回归方法识别财政转移支付对贫困县经济增长的因果效应。在政策截断值附近，县级收入的微小差异导致转移支付数额产生跳跃，通过比较截断值两侧的经济结果，识别净政策效应，结果显示扶贫转移支付对当地GDP有显著正向效应。",
    methodology_key: "Regression Discontinuity",
    highlights_en: ["regression discontinuity", "cutoff value", "forcing variable", "discontinuity", "bandwidth"],
    highlights_cn: ["断点回归", "截断值", "政策门槛", "跳跃", "带宽"]
  },
  {
    id: 8,
    title_en: "The Effect of Air Pollution on Mortality: Evidence from the Clean Air Act",
    title_cn: "空气污染与居民健康：基于两控区政策的断点回归研究",
    authors_en: "Chay, K. Y. & Greenstone, M.",
    authors_cn: "石磊, 张玉明",
    journal_en: "Journal of Political Economy",
    journal_cn: "经济研究",
    year_en: 2003,
    year_cn: 2017,
    abstract_en: "This paper estimates the effect of total suspended particulates (TSPs) on infant mortality using the Clean Air Act's regulatory structure as a source of exogenous variation in TSP reductions. Counties violating the Clean Air Act standards were required to reduce emissions, while those below the threshold were not. Using a regression discontinuity design around the regulatory threshold, a 1 percent reduction in TSPs leads to a 0.5 percent reduction in the infant mortality rate.",
    abstract_cn: "1998年，中国划定'两控区'以控制二氧化硫和酸雨污染，两控区与非两控区县级单位在污染治理力度上产生了系统性差异。本文利用这一政策准实验，以两控区划定标准附近的污染临界值构建断点回归设计，识别空气污染对居民呼吸道疾病死亡率的因果效应。结果显示PM2.5浓度每下降10微克，死亡率下降约2.3%。",
    methodology_key: "Regression Discontinuity",
    highlights_en: ["regression discontinuity", "regulatory threshold", "exogenous variation", "discontinuity"],
    highlights_cn: ["断点回归", "政策门槛", "外生变异", "准实验"]
  },
  {
    id: 9,
    title_en: "How Much Should We Trust Differences-in-Differences Estimates?",
    title_cn: "双重差分估计的可信度：基于中国省级面板数据的检验",
    authors_en: "Bertrand, M., Duflo, E. & Mullainathan, S.",
    authors_cn: "李平, 孙飞",
    journal_en: "Quarterly Journal of Economics",
    journal_cn: "经济学季刊",
    year_en: 2004,
    year_cn: 2016,
    abstract_en: "Most difference-in-differences (DD) papers rely on repeated cross-sectional or panel data spanning many years. We highlight the potential for serious bias due to serial correlation. When we implement the DD methodology on placebo laws, we find rejection rates of up to 45 percent. We show that standard errors computed after allowing for arbitrary serial correlation within states greatly reduce these over-rejections.",
    abstract_cn: "本文以中国28个省份1990—2015年的面板数据为样本，系统检验双重差分估计中序列相关问题的严重程度。当我们对安慰剂政策变量进行双重差分估计时，发现过度拒绝率高达43%。通过在省份层面允许任意形式的序列相关并进行聚类标准误修正，过度拒绝率降低至正常水平，与Bertrand等人的研究结论一致。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["difference-in-differences", "serial correlation", "placebo", "clustered standard errors"],
    highlights_cn: ["双重差分", "序列相关", "安慰剂检验", "聚类标准误"]
  },
  {
    id: 10,
    title_en: "Partisan Impacts on the Economy: Evidence from Prediction Markets and Close Elections",
    title_cn: "官员政治激励与地区经济增长：基于选举断点的研究",
    authors_en: "Snowberg, E., Wolfers, J. & Zitzewitz, E.",
    authors_cn: "李佳, 王民",
    journal_en: "Quarterly Journal of Economics",
    journal_cn: "管理世界",
    year_en: 2007,
    year_cn: 2019,
    abstract_en: "We estimate the economic impacts of presidential partisanship by comparing outcomes in events where the winner came close to losing versus events where the winner dominated. Our key identifying assumption is that close elections are as-good-as-random. Using a regression discontinuity design based on vote margins in US presidential elections, we find that Republican wins lead to higher stock prices but lower short-term output growth.",
    abstract_cn: "本文利用中国县委书记换届选举中得票差距接近的'准随机'特征构建断点回归设计，识别新任官员的个人特征对县域经济增长的因果效应。以官员是否具有经济学教育背景为处理变量，结果显示经济学背景官员任职期间GDP增速更高，政策取向更为市场化，提供了官员人力资本影响地方经济的因果证据。",
    methodology_key: "Regression Discontinuity",
    highlights_en: ["regression discontinuity", "close elections", "as-good-as-random", "vote margins"],
    highlights_cn: ["断点回归", "准随机", "得票差距", "因果识别"]
  },
  {
    id: 11,
    title_en: "Does Environmental Policy Reduce Industrial Emissions? Evidence from New Source Review",
    title_cn: "环境规制与企业排放：基于两控区政策的双重差分分析",
    authors_en: "Greenstone, M.",
    authors_cn: "石建平, 张越",
    journal_en: "American Economic Review",
    journal_cn: "经济研究",
    year_en: 2002,
    year_cn: 2017,
    abstract_en: "I examine the impact of the Clean Air Act's New Source Review program on industrial emissions. Using a differences-in-differences estimator that compares changes in emissions for plants in counties that switched from attainment to non-attainment status versus plants in counties that remained in attainment status, I find the program reduced particulate, sulfur dioxide, and nitrogen oxide emissions significantly.",
    abstract_cn: "本文利用中国1998年两控区划定这一外生政策冲击，以双重差分方法评估环境规制对工业二氧化硫排放的影响。将两控区内企业与两控区外企业进行比较，控制行业和地区固定效应后，结果显示政策实施后处理组排放量相对下降约14.7%，表明环境规制对企业减排具有显著政策效应。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["differences-in-differences", "attainment status", "treatment", "control"],
    highlights_cn: ["双重差分", "处理组", "控制组", "政策效应"]
  },
  {
    id: 12,
    title_en: "The Effect of Maternal Leave on Women's Career and Wages",
    title_cn: "产假政策与女性劳动参与：基于生育保险改革的研究",
    authors_en: "Waldfogel, J.",
    authors_cn: "陈婉华, 孙燕",
    journal_en: "ILR Review",
    journal_cn: "人口研究",
    year_en: 1998,
    year_cn: 2019,
    abstract_en: "This paper examines the effect of maternity leave coverage on women's wages and career trajectories. Using cross-state variation in the timing of mandated maternity leave legislation as a natural experiment with a differences-in-differences estimator, I find women with access to maternity leave are more likely to return to their pre-birth employer, leading to higher wages through job continuity.",
    abstract_cn: "2012年，中国修订《女职工劳动保护特别规定》，将产假由90天延长至128天，且各省对新规的执行时间存在差异。本文利用这一政策变化的跨省时间差异构建自然实验，以双重差分方法分析产假延长对女性劳动参与率和工资水平的影响。结果显示产假延长短期内降低了女性就业率但提高了工作稳定性。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["natural experiment", "differences-in-differences", "treatment", "maternity leave"],
    highlights_cn: ["自然实验", "双重差分", "产假政策", "处理组"]
  },
  {
    id: 13,
    title_en: "Immigration and the Neighborhood",
    title_cn: "流动人口与城市公共服务：基于历史定居工具变量的研究",
    authors_en: "Card, D.",
    authors_cn: "孟凡洁, 张磊",
    journal_en: "American Economic Journal: Applied Economics",
    journal_cn: "中国工业经济",
    year_en: 2009,
    year_cn: 2017,
    abstract_en: "I study the effect of immigration on housing, crime, and school quality in destination cities. I use an instrumental variables approach based on the historical settlement patterns of different nationality groups. Cities that received larger immigrant inflows from historically common origin countries in earlier decades tend to receive more immigrants today, allowing isolation of causal effects.",
    abstract_cn: "本文研究农村流动人口对中国城市公共服务的影响。利用各城市历史上接收特定籍贯流动人口的比例作为工具变量，我们识别流动人口规模对城市公共基础设施投入的外生影响。历史定居模式能够有效预测当期流动人口规模，且满足排他性约束，结果显示流动人口对城市公共服务投入有显著正向效应。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrumental variables", "historical settlement patterns", "instrument", "causal effects"],
    highlights_cn: ["工具变量", "历史定居模式", "排他性约束", "因果效应"]
  },
  {
    id: 14,
    title_en: "Incentives and Prosocial Behavior",
    title_cn: "激励机制与亲社会行为：基于中国志愿服务的随机对照实验",
    authors_en: "Fehr, E. & Gächter, S.",
    authors_cn: "钱学鹏, 王心怡",
    journal_en: "American Economic Review",
    journal_cn: "经济学季刊",
    year_en: 2002,
    year_cn: 2020,
    abstract_en: "We show in a controlled experiment that the introduction of monetary incentives can crowd out voluntary cooperation in social dilemmas. When monetary incentives are introduced, cooperation rates fall significantly below the level achieved without incentives. This crowding out of prosocial motivation has important implications for the design of incentive schemes in organizations.",
    abstract_cn: "本文通过在中国农村开展的随机对照实验，研究物质激励对自愿环保行为的影响。将村庄随机分配至现金奖励组、荣誉奖励组和无激励对照组，追踪三个月后居民垃圾分类参与率。结果表明物质激励存在显著的挤出效应，移除激励后处理组参与率反而低于对照组，与西方文献内在动机理论一致。",
    methodology_key: "Randomized Controlled Trial",
    highlights_en: ["controlled experiment", "monetary incentives", "crowding out", "treatment"],
    highlights_cn: ["随机对照实验", "挤出效应", "处理组", "对照组"]
  },
  {
    id: 15,
    title_en: "Bank Integration and State Business Cycles",
    title_cn: "金融开放与区域经济波动：银行跨省扩张的自然实验",
    authors_en: "Morgan, D. P., Rime, B. & Strahan, P. E.",
    authors_cn: "郝静文, 王天宇",
    journal_en: "Quarterly Journal of Economics",
    journal_cn: "金融研究",
    year_en: 2004,
    year_cn: 2018,
    abstract_en: "We estimate the effect of bank integration on state business cycles. Using the timing of branching deregulation across states as a natural experiment, we find that states that opened to out-of-state banking experienced less volatile output and employment cycles. Banking integration allows banks to sustain lending during downturns through cross-region insurance.",
    abstract_cn: "2006年起，中国允许国有银行在全国范围内设立跨省分支机构，形成金融市场整合的自然实验。本文利用各省与国有银行总部距离差异构造工具变量，识别银行跨区扩张对省际经济周期协动性的影响。结果显示，金融整合程度较高的省份GDP和就业波动显著降低，金融一体化起到了重要的风险分担作用。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["natural experiment", "timing of deregulation", "treatment", "differences-in-differences"],
    highlights_cn: ["自然实验", "工具变量", "双重差分", "风险分担"]
  },
  {
    id: 16,
    title_en: "Estimating the Effect of Unilateral Divorce on Women using the Panel Approach",
    title_cn: "新婚姻法与离婚率：基于面板数据的双重差分研究",
    authors_en: "Wolfers, J.",
    authors_cn: "张慧敏, 李建国",
    journal_en: "American Economic Review",
    journal_cn: "世界经济",
    year_en: 2006,
    year_cn: 2018,
    abstract_en: "Divorce law reforms swept across the United States during the 1970s. I exploit variation in the timing of divorce law reforms across states as a natural experiment, using a differences-in-differences estimator. I find that unilateral divorce laws raised divorce rates substantially and reduced rates of female suicide, domestic violence, and spousal murder.",
    abstract_cn: "2001年，中国新《婚姻法》的实施改变了离婚程序，降低了离婚门槛，且各省对新法实施力度和时间存在差异。本文利用这一政策变化的跨省差异构建自然实验，采用双重差分方法估计婚姻法改革对离婚率的影响。面板数据分析结果表明，新法实施后离婚率显著上升，家庭暴力发生率出现明显的抑制。",
    methodology_key: "Difference-in-Differences",
    highlights_en: ["differences-in-differences", "natural experiment", "timing of reforms", "panel data"],
    highlights_cn: ["双重差分", "自然实验", "面板数据", "政策改革"]
  },
  {
    id: 17,
    title_en: "Financing Innovation and Growth: Cash Flow, External Equity, and the 1990s R&D Boom",
    title_cn: "融资约束与企业创新：来自中国上市公司的证据",
    authors_en: "Brown, J. R., Fazzari, S. M. & Petersen, B. C.",
    authors_cn: "胡文洁, 刘博远",
    journal_en: "Journal of Finance",
    journal_cn: "金融研究",
    year_en: 2009,
    year_cn: 2020,
    abstract_en: "We show that cash flow and external equity finance have large effects on R&D for small, young firms but much smaller effects for large, mature firms. These differences confirm the importance of financial constraints for young innovative firms. The boom in R&D spending during the 1990s was largely fueled by expanded access to external equity financing through public equity markets.",
    abstract_cn: "本文利用中国上市公司面板数据，研究融资约束对企业研发投入的影响。以公司规模和股权集中度作为融资约束的代理变量，采用固定效应模型和工具变量方法，发现现金流对中小上市公司研发支出的影响显著大于大型国有企业。股票市场的发展通过缓解融资约束对中小企业创新有显著促进作用。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["financial constraints", "instrumental variable", "cash flow", "R&D"],
    highlights_cn: ["融资约束", "工具变量", "研发投入", "面板数据"]
  },
  {
    id: 18,
    title_en: "Inequality and Growth: What Can the Data Say?",
    title_cn: "不平等与经济增长：基于中国省级动态面板的GMM研究",
    authors_en: "Banerjee, A. V. & Duflo, E.",
    authors_cn: "黄荣贵, 张学良",
    journal_en: "Journal of Economic Growth",
    journal_cn: "经济研究",
    year_en: 2003,
    year_cn: 2018,
    abstract_en: "We show that the net effect of inequality on growth is non-linear and non-monotonic. An increase in inequality in a country with initially low inequality hurts growth, while in a country with initially high inequality it may raise growth. We document this using a large cross-country panel dataset and show results are robust to GMM estimation and fixed effects.",
    abstract_cn: "本文利用中国1985—2015年省级面板数据，采用GMM动态面板方法研究收入不平等与经济增长的动态关系。以基尼系数衡量不平等程度，以人均GDP增长率衡量经济增长。估计结果显示，在低收入省份收入不平等加剧对增长有负效应，而在高收入省份影响不显著，表明不平等与增长的关系具有非线性特征，与Banerjee & Duflo的理论预测一致。",
    methodology_key: "GMM Panel",
    highlights_en: ["GMM", "panel data", "non-linear", "fixed effects", "inequality"],
    highlights_cn: ["GMM", "动态面板", "非线性", "固定效应", "不平等"]
  },
  {
    id: 19,
    title_en: "The Long-Run Effects of the Scramble for Africa",
    title_cn: "历史边界与区域发展：中国历史政区分割的长期影响",
    authors_en: "Michalopoulos, S. & Papaioannou, E.",
    authors_cn: "许成刚, 叶盛",
    journal_en: "American Economic Review",
    journal_cn: "经济学季刊",
    year_en: 2016,
    year_cn: 2022,
    abstract_en: "We examine the long-run consequences of the Scramble for Africa, during which European powers arbitrarily split ethnic groups across national boundaries. We use this partition as a natural experiment and find that partitioned ethnic groups have lower living standards and face more conflict. These effects are robust to controlling for geographic, historical, and ethnic-group characteristics.",
    abstract_cn: "本文研究清代行政区划划分对现代中国县域经济发展的长期影响。利用清代州县边界与现代县级边界的重叠程度差异作为历史制度变量，采用断点回归和工具变量方法，发现历史上被清代统一行政区管辖的相邻县域经济差距显著小于被不同行政单元管辖的县域，表明历史边界通过持久的制度和社会资本差异影响现代经济。",
    methodology_key: "Historical Natural Experiment",
    highlights_en: ["natural experiment", "arbitrary partition", "long-run consequences", "robust"],
    highlights_cn: ["自然实验", "历史边界", "长期影响", "稳健性"]
  },
  {
    id: 20,
    title_en: "The Economic Effects of Mass Migration: Evidence from the Great Black Migration",
    title_cn: "人口流动与城市经济：基于中国城镇化的自然实验研究",
    authors_en: "Boustan, L. P.",
    authors_cn: "刘晓庆, 张伟",
    journal_en: "Review of Economics and Statistics",
    journal_cn: "中国工业经济",
    year_en: 2010,
    year_cn: 2021,
    abstract_en: "I estimate the economic impacts of the Great Black Migration on destination cities using the historical distribution of Black southerners across states as an instrumental variable for migration flows. Cities that received more migrants experienced lower wages for low-skilled workers. Instrumental variable estimates suggest each migrant reduced wages of competing workers by 2.5 percent.",
    abstract_cn: "本文以中国1990—2015年的城镇化浪潮为背景，利用各城市历史人口分布作为工具变量，估计大规模农业劳动力转移对城市劳动力市场的影响。工具变量估计结果显示，流动人口大量涌入使城市低技能工人工资相对下降约2.8%，同时城市人均GDP和劳动生产率显著提升，表明流动人口提高了城市整体生产效率。",
    methodology_key: "Instrumental Variable",
    highlights_en: ["instrumental variable", "historical distribution", "instrument", "migration flows"],
    highlights_cn: ["工具变量", "历史分布", "流动人口", "因果估计"]
  }
];
